site_name: flacco Tutorial
repo_url: https://github.com/kerschke/flacco
pages:
- [index.md, "flacco"]
- [quickstart.md, "Introduction", "Quick Start"]
- [ela.md, "Features", "Classical Exploratory Landscape Analysis"]
- [cm.md, "Features", "Cell Mapping"]
- [gcm.md, "Features", "Generalized Cell Mapping"]
- [barriertrees.md, "Features", "Barrier Trees"]
- [dispersion.md, "Features", "Dispersion"]
- [ic.md, "Features", "Information Content"]
- [nbf.md, "Features", "Nearest Better Clustering"]
- [misc_features.md, "Features", "Miscellaneous"]
- [visualisations.md, "Miscellaneous", "Visualisations"]
theme: spacelab
markdown_extensions: [smartypants]