site_name: flacco Tutorial
repo_url: https://github.com/kerschke/flacco
pages:
- [index.md, "flacco"]
- [quickstart.md, "Introduction", "Quick Start"]
- [cm.md, "Cell Mapping Features", "Simple Cell Mapping"]
- [gcm.md, "Cell Mapping Features", "Generalized Cell Mapping"]
- [barriertrees.md, "Cell Mapping Features", "Barrier Trees"]
- [ic.md, "Extended Features", "Information Content"]
theme: readthedocs
markdown_extensions: [smartypants]